language: go
sudo: false
go: stable
install: "# skip"

script:
  - go vet
  - GOOS=linux GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_linux-amd64"
  - GOOS=darwin GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_darwin-amd64"
  - GOOS=windows GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_windows-amd64.exe"

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  file_glob: true
  file: "csv2geojson_*"
  api_key:
    secure: "V6PyvL+yh8LtKtXh8Yj78KBtLHOzH6KU0Cd3wYRYlyJG/xT9nm5oFHFHPlOBO/xU1cx1/b0TGzXKGQhYiF/2f5nSipF8ZUo3d6BchGibNqOBWvjK6U82UKGmXP94gJLAWZg+/h6XY1XUtoD8aYveRQMqZCSFMvcLF6owVjAEs4kBMVgEU9+NskYaYHpuCwVD2Wm7mjFt8apJ7tpKvfXY4OV5cDk7HAY+bG4rkVIwbVMaQ6ffyNahftHeYJKNG7szHtux+LBf5eKS6v4oTMMUAac1krPNBjK/4i19JtjQ5QWcm6ZSGvMsZriKz2ztj8BFFyTXKHXX8ktubTXsGtuzSQhng6QISY9SpJFXLnQ8tEGL9jPMxRKdtYgXHE5Y1VuHpx+jzJKzQcR+F5/YHB6uWxNj6MAiAmS8tOBOzWXjzm1sb2K7JGvkxF5VPyJuV7dwPkXmRknO8uYiwZfG04WqFgkz3vzCoh+DswZ1U6SBqyC3u0uXfsUNS6t2rYSrrFybbGOfM3vFpHrEgg3HNmGnYhIdBqXnkac/fS5WAd+FgfLmWqAYPDTdVSfSD7WCAfUg74R7lYABP9J7qWkr8KAX5kr0IVdk8r5kNtAXZjj+D/SizrbNAcNjmtcHg6mADo8auXviOrOjWlqX/ITOZwGoroY3sNtn8bg1+ouCAc8nRbU="
  on:
    repo: pvernier/csv2geojson
tags: true
