language: go
sudo: false
go: stable
install: "# skip"
script:
- go vet
- GOOS=linux GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_linux-amd64"
- GOOS=darwin GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_darwin-amd64"
- GOOS=windows GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_windows-amd64.exe"
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: csv2geojson_*
  api_key:
    secure: "UhPATXfq2tYXWUokfQckZ/naaD6yrSaVuBxb2ASFzb6WsMYC4w/8AcoN3UnECa6iYlWpuouE2mYFXYW69OhJLstCiojobojlrMJ4x7xbfYJ5UWXsdyMZWOq5jWa2620UEcH6pivKDs/UTDpRu+NZqupCUv/dY5sSndU1sO4YRlLorqoCbu6dqI8DKvrw4M34kwjUHMccVMXbVFcayJmldSQ94dxVYahN7zGr+atZLUNPNgXdKKad7rSiCenDCvzRvYkljwWLZBov4mbE6YDw/uhC3muvoufO4kwKhmokpw0u6QZRbuUU6/VYfp9BHA7Z1ZzK2euPKhX8FGtlylf63urzFPfYKVCe0y52S5jfellu76/4qZku0fnsLz/WHXdJQO1fEWI+0z8kWuoi7tQba6N263WK1AV6Rr5ordrdqcq/N8fSNnPB1zZmIcnRAHBn9N2GKUmN0uTPgeZqpVxw16mkCHclbqQBipNsy6lqcXvTxti+lJC6WeUww/ePiKbEOU6McFuOVE2xgqijYkgpLWXPzxn6S8VTm0n19+s+PG+2Fv4iLa4b9DvvARRKNRaDPAsbYvcCNugnXXLd2t2LfZDPT+8BHP/M4uyB0chs8Q0iWuOU/eGAo96Ho+RPvlvdHp5CuvsZ5jdPa5rpuvMGo1CnWC8TGzdtUP48dlIsTwc="
  on:
    repo: pvernier/csv2geojson
    tags: true

  
