language: go
sudo: false
go: stable
install: "# skip"

script:
  - go vet
  - GOOS=linux GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_linux-amd64"
  - GOOS=darwin GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_darwin-amd64"
  - GOOS=windows GOARCH=amd64 go build -o "csv2geojson_$(git describe --tags)_windows-amd64.exe"

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  file_glob: true
  file: "csv2geojson_*"
  api_key:
    secure: "JM0a1WANwxkqnkjkL02FT3UusdxfANMUbFui6oX+yINrYStsFelXZOkm8byBYXOnq4MWmfUx6iJ58R9hzCkbFV6jNI8fuFeIClQJzp6yRnJG/lA5cZ2+fhUIFsxp+Y4N69tNqjIaqsrTD4tZGg8Z6egyMg0CYgmCS0wgJIYD4paQaS8f5tYb0uLkMkqNpK0FXUtUKUTNkrKLwxWPHNzyLXiayhQUXgUo5XwTQIkAuW2g4GQPwPjUS6J9BLqldle77nNecAEo6d4rfflHMLAGVPNAH/Hralc6VVtsK0XaGPJMOWvAq5RdY5U8w9fXVxTrejTob8ULtFECQGw3TuenWKcZNNVR3n/DAgnTs5WyGdwSHjyryQjLj21/XhSC8URXuQDpuL974d1XcT/PehMi2n5q0aRYKlQqHMUCVj5qd/Zkn8KC48srkQAPwiNH2arMF1p+HH9K26gMBeg589Jk4KycHW4kKbKynvPf6A8NRRwLt5ALqlpS4rJ6HnDaA1dlUgtfygVXMQ6f1FWn4g5vgym83WFkoUxUotKSrUC7lyZ4CGLM4F5THEZNUDA8rCApDZUw1EYT9cIsIOgdd+9Z2W9D7DKNWBuPL7RA0kr8apAoGN1KSqEFWl+4DeOYdrF/lO6ewQaYbVXRu+wI5IKqHIIvh8YCVzp9PQi2ehBSkO4="
  on:
    repo: pvernier/csv2geojson
tags: true
